"""Generate the Word content-control tag table from the item schema.

The tags *are* the schema's field names (tech doc 4.4).  Deriving the table from
the Pydantic model rather than maintaining it by hand is what keeps that true:
a field rename changes the spec on the next run instead of silently leaving the
template pointing at a field that no longer exists.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pydantic import BaseModel

from schemas.aufgabe import Aufsichtsarbeit

TARGET = Path(__file__).resolve().parents[1] / "docio" / "template_tags.md"

# Elements that repeat in the document and therefore need a repeating section
# control rather than a plain text control.
REPEATING = {"teilaufgaben": "ta", "erwartungspunkte": "eh"}


def type_label(annotation) -> str:
    text = str(annotation).replace("typing.", "").replace("<class '", "").replace("'>", "")
    for module in ("schemas.aufgabe.", "builtins."):
        text = text.replace(module, "")
    return text.replace("Optional[", "").replace("]", "") if text.startswith("Optional[") else text


def walk(model: type[BaseModel], prefix: str = "", depth: int = 0) -> list[dict]:
    rows: list[dict] = []
    for name, field in model.model_fields.items():
        tag = f"{prefix}{name}"
        annotation = field.annotation
        inner = None
        # Unwrap Optional[...] and list[...] to find a nested model.
        for candidate in getattr(annotation, "__args__", ()) or ():
            if isinstance(candidate, type) and issubclass(candidate, BaseModel):
                inner = candidate
        if isinstance(annotation, type) and issubclass(annotation, BaseModel):
            inner = annotation

        rows.append(
            {
                "tag": tag,
                "control": (
                    "repeating section"
                    if name in REPEATING
                    else "group" if inner and name not in REPEATING else "plain text"
                ),
                "type": type_label(annotation),
                "repeating": name in REPEATING,
                "description": field.description or "",
                "depth": depth,
            }
        )
        if inner is not None and depth < 3:
            rows.extend(walk(inner, prefix=f"{tag}.", depth=depth + 1))
    return rows


def main() -> int:
    rows = walk(Aufsichtsarbeit)
    lines = [
        "<!-- generated by scripts/generate_template_spec.py — do not edit by hand -->",
        "# Content-control tag table",
        "",
        f"{len(rows)} tags, derived from `schemas/aufgabe.py::Aufsichtsarbeit`.",
        "",
        "| Tag | Control type | Schema type | Notes |",
        "|---|---|---|---|",
    ]
    for row in rows:
        indent = "&nbsp;" * (row["depth"] * 4)
        lines.append(
            f"| {indent}`{row['tag']}` | {row['control']} | `{row['type']}` | {row['description']} |"
        )
    lines.append("")
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(rows)} tags to {TARGET.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
